apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: wordcount-mpi
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 60
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          volumes:
            - name: mpi-data
              hostPath:
                path: /mnt/mpi-data
                type: Directory
          containers:
          - image: puida/mpi-wordcount:latest
            name: mpi-launcher
            securityContext:
              runAsUser: 1000
            command:
            - bash
            args:
            - -c
            - time mpirun -n "4" /home/mpiuser/contaPalavras
            volumeMounts:
              - name: mpi-data
                mountPath: /data
    Worker:
      replicas: 4
      template:
        spec:
          volumes:
            - name: mpi-data
              hostPath:
                path: /mnt/mpi-data
                type: Directory
          containers:
          - image: puida/mpi-wordcount:latest
            name: mpi-worker
            securityContext:
              runAsUser: 1000
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            volumeMounts:
              - name: mpi-data
                mountPath: /data
